name: Check Links

on:
  pull_request:

jobs:
  link-check:
    runs-on: ubuntu-latest
    name: Check Docs links
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive
          
      - name: Import External Doc
        run: pwsh ./doc/import_external_docs.ps1
        
      - name: Wait for external docs to exist
        run: |
          for i in {1..30}; do
            if [ -d "./articles/external" ]; then
              echo "✅ External docs found."
              exit 0
            else
              echo "⏳ Waiting for ./articles/external to appear..."
              sleep 1
            fi
          done
          echo "❌ Timeout: external docs not found after 30 seconds."
          exit 1
    
      - name: Check links
        uses: lycheeverse/lychee-action@v1.9.0
        with:
          args: >
            --verbose
            --no-progress
            --cache-exclude-status 429
            ./doc/**/*.md
            ./articles/**/*.md
            
