name: Check Links

on:
  pull_request:

jobs:
  link-check:
    runs-on: ubuntu-latest
    name: Check Docs links
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive

      - name: Check links
        uses: lycheeverse/lychee-action@v1.9.0
        with:
          args: >
            --verbose
            --no-progress
            ./doc/**/*.md
      
